-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        layout = "dwindle",
        border_size = 4,
        gaps_in = 4,
        gaps_out = 6,
        -- Coffee inactive
        -- Light cream active
        allow_tearing = true,
        col = {
            inactive_border = "0xff6f4e37",
            active_border = "0xffD1BB9E",
        },
    },
})

hl.config({
    decoration = {
        rounding = 24,
    },
})
