-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Rice Template - Hyprland Borders Configuration

hl.config({
    general = {
        layout = "dwindle",
        border_size = 3,
        gaps_in = 4,
        gaps_out = 4,
        -- Example inactive
        -- Example active
        allow_tearing = true,
        col = {
            inactive_border = "0xffb0c4de",
            active_border = "0xff7aa2f7",
        },
    },
})

hl.config({
    decoration = {
        rounding = 24,
    },
})
