# Example Rice - Kitty Configuration
font_family      Meslo LG M
font_size        16

# Example rice Theme
foreground       #d8dee9
background       #0e1113
cursor           #dbab58

# Black
color0           #5264ad
color8           #5264ad

# Red
color1           #dbab58
color9           #dbab58

# Green
color2           #5264ad
color10          #5264ad

# Yellow
color3           #dbab58
color11          #dbab58

# Blue
color4           #5264ad
color12          #5264ad

# Magenta
color5           #dbab58
color13          #dbab58

# Cyan
color6           #5264ad
color14          #5264ad

# White
color7           #e5e9f0
color15          #eceff4

# Window settings
window_padding_width 10
confirm_os_window_close 0

# opacity
background_opacity 0.6
