-- Auto-generated by rice switching script for rice: FrutigerAero
-- Generated on: Fri Nov 14 02:26:25 PM UTC 2025
return {
    -- Base colors
    rosewater = "#ECF0F1",
    flamingo = "#FF8C00",
    pink = "#0078d7",
    mauve = "#0078d7",
    red = "#FF8C00",
    maroon = "#FF8C00",
    peach = "#FF8C00",
    yellow = "#FF8C00",
    green = "#00C853",
    teal = "#00C853",
    sky = "#00C853",
    sapphire = "#0078d7",
    blue = "#0078D7",
    lavender = "#0078d7",

    -- Text colors
    text = "#E0E0E0",
    subtext1 = "#BDC3C7",
    subtext0 = "#4C566A",
    overlay2 = "#4C566A",
    overlay1 = "#4C566A",
    overlay0 = "#4C566A",

    -- Surface colors
    surface2 = "#4C566A",
    surface1 = "#1A1D22",
    surface0 = "#1A1D22",
    base = "#000000",
    mantle = "#1A1D22",
    crust = "#1A1D22",
}
