-- Auto-generated by rice switching script for rice: Rainbow
-- Generated on: Fri Nov  7 02:57:03 PM UTC 2025
return {
    -- Base colors
    rosewater = "#ffffff",
    flamingo = "#ff8e8e",
    pink = "#9775fa",
    mauve = "#845ef7",
    red = "#ff6b6b",
    maroon = "#ff8e8e",
    peach = "#ffd43b",
    yellow = "#ffe066",
    green = "#51cf66",
    teal = "#22b8cf",
    sky = "#3bc9db",
    sapphire = "#74c0fc",
    blue = "#339af0",
    lavender = "#74c0fc",

    -- Text colors
    text = "#ffffff",
    subtext1 = "#ffffff",
    subtext0 = "#54487a",
    overlay2 = "#54487a",
    overlay1 = "#54487a",
    overlay0 = "#54487a",

    -- Surface colors
    surface2 = "#54487a",
    surface1 = "#2d1b69",
    surface0 = "#2d1b69",
    base = "#000000",
    mantle = "#2d1b69",
    crust = "#2d1b69",
}
