-- Auto-generated by rice switching script for rice: Bubble
-- Generated on: Thu Oct 23 03:11:01 PM UTC 2025
return {
    -- Base colors
    rosewater = "#eceff4",
    flamingo = "#bf616a",
    pink = "#eeade8",
    mauve = "#eeade8",
    red = "#bf616a",
    maroon = "#bf616a",
    peach = "#ebcb8b",
    yellow = "#ebcb8b",
    green = "#a3be8c",
    teal = "#88c0d0",
    sky = "#8fbcbb",
    sapphire = "#81a1c1",
    blue = "#81a1c1",
    lavender = "#81a1c1",

    -- Text colors
    text = "#d8dee9",
    subtext1 = "#e5e9f0",
    subtext0 = "#4c566a",
    overlay2 = "#4c566a",
    overlay1 = "#4c566a",
    overlay0 = "#4c566a",

    -- Surface colors
    surface2 = "#4c566a",
    surface1 = "#3b4252",
    surface0 = "#3b4252",
    base = "#2e3440",
    mantle = "#3b4252",
    crust = "#3b4252",
}
