-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        layout = "dwindle",
        border_size = 4,
        gaps_in = 4,
        gaps_out = 11,
        allow_tearing = true,
        col = {
            inactive_border = "0xff3a3352",
            active_border = "0xff6E5BAA",
        },
    },
})

hl.config({
    decoration = {
        rounding = 4,
    },
})
