-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        layout = "dwindle",
        border_size = 3,
        gaps_in = 4,
        gaps_out = 11,
        -- Dark red inactive
        -- Darker red active
        allow_tearing = true,
        col = {
            inactive_border = "0xff1a0000",
            active_border = "0xff990000",
        },
    },
})

