-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        layout = "master",
        border_size = 4,
        gaps_in = 4,
        gaps_out = 6,
        -- purple light 
        -- lavender
        allow_tearing = true,
        col = {
            inactive_border = "0xff6e56af",
            active_border = "0xffdddfff",
        },
    },
})

hl.config({
    decoration = {
        rounding = 0,
    },
})
