general {
    layout = dwindle
    border_size = 4
    gaps_in = 4
    gaps_out = 10
    col.inactive_border =  rgba(5264adFF) # Inactive
    col.active_border =  rgba(dbab58FF) # Active
    allow_tearing = true
}

decoration {
    rounding = 4
}
