-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        layout = "master",
        border_size = 4,
        gaps_in = 4,
        gaps_out = 10,
        -- Inactive
        -- Active
        allow_tearing = true,
        col = {
            inactive_border = "rgba(5264adFF)",
            active_border = "rgba(dbab58FF)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 4,
    },
})
