-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        layout = "dwindle",
        border_size = 4,
        gaps_in = 4,
        gaps_out = 11,
        -- Nordic inactive
        -- Light yellow active
        allow_tearing = true,
        col = {
            inactive_border = "0xff434C5E",
            active_border = "0xfff9d9a6",
        },
    },
})

hl.config({
    decoration = {
        rounding = 15,
    },
})
