-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        layout = "dwindle",
        border_size = 1,
        gaps_in = 5,
        gaps_out = 11,
        allow_tearing = true,
        col = {
            inactive_border = { "rgb(18", 18, "18)" },
            active_border = { "rgb(18", 18, "18)" },
        },
    },
})

hl.config({
    decoration = {
        rounding = 12,
    },
})
