-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        layout = "dwindle",
        border_size = 4,
        gaps_in = 4,
        gaps_out = 6,
        -- H3cker inactive
        -- H3cker active
        allow_tearing = true,
        col = {
            inactive_border = "0xff60b484",
            active_border = "0xff00ff94",
        },
    },
})

hl.config({
    decoration = {
        rounding = 0,
    },
})
