-- Auto-generated by rice switching script for rice: WinXP
-- Generated on: Sat Dec 13 01:33:32 PM UTC 2025
return {
    -- Base colors
    rosewater = "#f7f7f5",
    flamingo = "#e04c02",
    pink = "#ffd11b",
    mauve = "#ffd11b",
    red = "#e04c02",
    maroon = "#e04c02",
    peach = "#ffd11b",
    yellow = "#ffd11b",
    green = "#7dc302",
    teal = "#b02f30",
    sky = "#b02f30",
    sapphire = "#7b96fd",
    blue = "#7b96fd",
    lavender = "#7b96fd",

    -- Text colors
    text = "#d8dee9",
    subtext1 = "#d9d9d7",
    subtext0 = "#808080",
    overlay2 = "#808080",
    overlay1 = "#808080",
    overlay0 = "#808080",

    -- Surface colors
    surface2 = "#808080",
    surface1 = "#151515",
    surface0 = "#151515",
    base = "#000000",
    mantle = "#151515",
    crust = "#151515",
}
