general {
    layout = dwindle
    border_size = 4
    gaps_in = 4
    gaps_out = 6
    col.inactive_border = 0xffc4a000 # Inactive
    col.active_border = 0xfffcc000    # Active
    allow_tearing = true
}

decoration {
    rounding = 0
}
