-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        layout = "dwindle",
        border_size = 4,
        gaps_in = 4,
        gaps_out = 6,
        -- Inactive
        -- Active
        allow_tearing = true,
        col = {
            inactive_border = "0xffc4a000",
            active_border = "0xfffcc000",
        },
    },
})

hl.config({
    decoration = {
        rounding = 0,
    },
})
